// <auto-generated />
using System;
using EntityframworkCodeFirst.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityframworkCodeFirst.Migrations
{
    [DbContext(typeof(apiDBcontext))]
    [Migration("20210303034320_111")]
    partial class _111
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityframworkCodeFirst.Model.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Price");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("EntityframworkCodeFirst.Model.Job", b =>
                {
                    b.Property<int?>("Jobid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Job_desc");

                    b.HasKey("Jobid");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("EntityframworkCodeFirst.Model.Publisher", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("EntityframworkCodeFirst.Model.Users", b =>
                {
                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email_address");

                    b.Property<string>("First_name");

                    b.Property<DateTime?>("Hire_date");

                    b.Property<int?>("JobId");

                    b.Property<string>("Job_level");

                    b.Property<string>("Last_name");

                    b.Property<string>("Middle_name");

                    b.Property<string>("Password");

                    b.Property<int?>("Pub_id");

                    b.Property<int?>("publisherId");

                    b.HasKey("UserId");

                    b.HasIndex("JobId");

                    b.HasIndex("publisherId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EntityframworkCodeFirst.Model.Users", b =>
                {
                    b.HasOne("EntityframworkCodeFirst.Model.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("EntityframworkCodeFirst.Model.Publisher", "publisher")
                        .WithMany()
                        .HasForeignKey("publisherId");
                });
#pragma warning restore 612, 618
        }
    }
}
